image: maven:latest

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test
sonarcloud-check:
  image: maven:latest
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar
  only:
    - merge_requests
    - master
    - develop
deploy :
  stage: deploy
    script:
      - ssh-add <(echo "$STAGING_PRIVATE_KEY")
      - ssh -p22 maclef@35.195.21.10 "sudo -s rm /produits/tomcat/webapps/epsi-contrat.war && rm -r /produits/tomcat/webapps/epsi-contrat"
      - scp -P22 -r target/epsi-contrat.war maclef@35.195.21.10:htdocs/produits/tomcat/webapps/
