image: maven:latest

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

    
deploy:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - ssh -p22 maclef@35.195.21.10 "sudo -s rm /produits/tomcat/webapps/epsi-contrat.war && rm -r /produits/tomcat/webapps/epsi-contrat"
    - scp -P22 -r target/epsi-contrat.war maclef@35.195.21.10:htdocs/produits/tomcat/webapps/
